wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1719201271
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 53
      - 54
      - 55
      3:
      - 23
      4: 3.11.9
      5: 0.17.2
      6: 4.41.2
      8:
      - 2
      - 5
      13: darwin-arm64
